---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  options:
    force: true
    ignore-certs: false
    ignore-errors: false
    role-file: "{{ MOLECULE_SCENARIO_DIRECTORY }}/../default/requirements.yml"
    requirements-file: "{{ MOLECULE_SCENARIO_DIRECTORY }}/../default/requirements.yml"


platforms:
  - name: slm-ansible-role-litellm-host
    groups:
      - slm_ansible_role_litellm_host
      - litellm
    # Kubevirt
    image: quay.io/containerdisks/ubuntu:24.04
    # Openstack
    image_name: Ubuntu 24.04 64-bit


ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

  playbooks:
    create: create-kv.yml
    destroy: destroy-kv.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
